# Generated by Django 4.1 on 2022-09-01 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Loja', '0002_cliente_pedido_pedidoitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidoitem',
            name='pedido',
        ),
        migrations.AddField(
            model_name='pedido',
            name='itens',
            field=models.ManyToManyField(to='Loja.pedidoitem'),
        ),
    ]
